### ISSUE TITLE
Ability to work in a groupchat with topics

### ISSUE THREAD

**Issue by art-kslv** [beradeep/whitehole#1]
Could you please make tobwork with a group chat with topics

**Comment by beradeep** [comment]
What could you please elaborate on what you mean by a group chat with topics? It already works in a group chat.

**Comment by art-kslv** [comment]
In superchats they are topics.
Do you think it will be possible to implement?
https://telegram.org/blog/topics-in-groups-collectible-usernames

Your idea is great!!!

I also found that the compression is a bit too high

**Comment by art-kslv** [comment]
I assume, it this parameter

https://core.telegram.org/bots/api#available-methods:~:text=%40channelusername)-,message_thread_id,target%20message%20thread%20(topic)%20of%20the%20forum%3B%20for%20forum%20supergroups%20only,-text

**Comment by beradeep** [comment]
Yeah, you're correct. But currently the library I'm using as a wrapper over the telegram api, seems to not have support for the `message_thread_id` parameter. Can you provide any strong use case, for supporting supergroups/forums?

**Comment by beradeep** [comment]
For the compression, how much do you feel is ideal?
