### ISSUE TITLE
Parsing Package Error.

### ISSUE THREAD

**Issue by MAAB-FW** [beradeep/whitehole#16]
- [ ] App version = 0.6
- [ ] Android version = 8
- [ ] Device = Oppo A3s (CPH1853)

## Bug description
Can't install this app. It's says, "There was a problem parsing the package". Is this app only for upper version of android?

## Screenshots
![Screenshot_2024-08-27-23-27-50-85](https://github.com/user-attachments/assets/b809fc86-a386-43f4-9d3b-978f59a80a5d)

**Comment by beradeep** [comment]
Yes. Right now, the min. supported version for this app is Android 10.
