### ISSUE TITLE
Not working on Android 10

### ISSUE THREAD

**Issue by prono69** [beradeep/whitehole#2]
Hi, I am using Android 10 rom . When I try to install this app, it's showing this ![Screenshot_20240713-131639655.jpg](https://github.com/user-attachments/assets/fc0aa129-3158-4382-bc1b-c99fb9a54276)

**Comment by beradeep** [comment]
Hi, I'm sorry the app currently supports API 30+ (Android 11+). I'm working on lowering the minimum supported sdk.

**Comment by prono69** [comment]
> Hi, I'm sorry the app currently supports API 30+ (Android 11+). I'm working on lowering the minimum supported sdk.

Oh I guess that's why ... I would highly appreciate it if it's support Android 10 🙏😊

**Comment by beradeep** [comment]
Hi, checkout `v0.4`. I hope it works! 😄

**Comment by prono69** [comment]
Wow it's really working. Thanks bro ❤️
Mission Passed. Respect+++
