### ISSUE TITLE
Upload with proper file extensions 

### ISSUE THREAD

**Issue by tromshusky** [beradeep/whitehole#29]
## Please confirm the following

- [x] I've checked [the current issues](https://github.com/beradeep/whitehole/issues) for duplicate issues.
- [x] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [x] My issue is well-defined and aligns with the goal of the project.

## Description
when i open the chat in Telegram, its just files, but i would like to see photos.
can we upload the files with proper extensions?

**Comment by tromshusky** [comment]
might be a nug, since i just saw its getting uploaded with a missing dot 456789[.]jpg

**Comment by tromshusky** [comment]
likely to fix here?
https://github.com/beradeep/whitehole/blob/173eedf8296542d7e3a0dda05a75bb8b9f458f0e/app/src/main/java/com/bera/whitehole/workers/PeriodicPhotoBackupWorker.kt#L79

**Comment by beradeep** [comment]
fixed by #31.
