### ISSUE TITLE
Media file type 

### ISSUE THREAD

**Issue by WALTercy** [beradeep/whitehole#32]
## Please confirm the following

- [x ] I've checked [the current issues](https://github.com/beradeep/whitehole/issues) for duplicate issues.
- [x ] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [x ] My issue is well-defined and aligns with the goal of the project.

## Description

I've seen on the group chat the photos are uploaded but the file extensions are missing or unidentifiable by telegram. Making it impossible to directly open it on telegram as a photo.
Can you add modify the filename to contain file type extension on telegram 
![Screenshot_20241026-071948](https://github.com/user-attachments/assets/92bd4bd3-2c1d-4bac-9953-f675e0789dca)

**Comment by beradeep** [comment]
just to let you know, this is fixed, and will come up in the next release
