### ISSUE TITLE
Recover Data

### ISSUE THREAD

**Issue by urvyn** [beradeep/whitehole#34]
Unfortunately my mobile phone broke a few weeks ago.

Is it possible for me to get access to my data again?
I have tried to using the old token again but doesn't work.

Nice greetings

**Comment by beradeep** [comment]
Hey @urvyn sorry to hear that. To get back all the images, firstly you would need the local database backup file, which would be created by the app if you had the `database backup` option enabled in the app settings. Were you able to recover any data from that phone. With that file you can import all the images back.

**Comment by urvyn** [comment]
Hi @beradeep  
my old phone won't turn on anymore and trying connect with my pc too but I can't get access to the phone storage.

Thanks you for your answers.

**Comment by beradeep** [comment]
Ahh, sad to hear that ☹️
