### ISSUE TITLE
Feedback on Backup Feature: Suggestions for Improvements

### ISSUE THREAD

**Issue by Jaizm6** [beradeep/whitehole#4]
I tested out this backup feature and think it's a great initiative by the developer. However, there are a couple of things that could be improved:

1. Currently, only one file can be backed up at a time. Implementing a multi-select feature could greatly enhance the user experience.

2. One major issue I encountered was that after uninstalling and re-installing the app, I was unable to access my previously backed up data that is still in the Telegram group. This is a crucial issue that needs to be addressed.

**Comment by beradeep** [comment]
Hi, thanks for providing feedback!
> 1. Currently, only one file can be backed up at a time. Implementing a multi-select feature could greatly enhance the user experience.

Yes, you're correct. I'm working on the multi-select and upload feature. However, there a periodic backup feature for backing up all photos on your device in the settings, which I guess you've explored.

> 2. One major issue I encountered was that after uninstalling and re-installing the app, I was unable to access my previously backed up data that is still in the Telegram group. This is a crucial issue that needs to be addressed.

The goal of the app was to have users control all of their data. That's why there's the export and import database feature. You can have your entire database exported in `.json` file, so that when you reinstall the app you can import the database again from that file.

**Comment by Jaizm6** [comment]
That is correct. Due to Telegram's file size limits, if your backup file is
10GB, you will not be able to export it all at once on Telegram. You may
need to split the file into smaller chunks or use an alternative method to
transfer your data.

**Comment by beradeep** [comment]
The `Export backup database` button only creates a file that stores the database and saves it to your device's local storage. This file doesn't get uploaded to Telegram. You need to keep this file in order to import the database back, in case the app is uninstalled and reinstalled.

**Comment by samolukadjo** [comment]
> The `Export backup database` button only creates a file that stores the database and saves it to your device's local storage. This file doesn't get uploaded to Telegram. You need to keep this file in order to import the database back, in case the app is uninstalled and reinstalled.

I don't know how hard it would be, but could the app periodically create and backup this database file? It could be in another Telegram group or trough some other means. Since this file is pretty important for having access to your data

**Comment by beradeep** [comment]
Hi, @Jaizm6 @samolukadjo checkout the latest release.

**Comment by samolukadjo** [comment]
@beradeep Well done 👍
