### ISSUE TITLE
Feature Request: Option to disable auto periodic backup on mobile data

### ISSUE THREAD

**Issue by Wans22** [beradeep/whitehole#5]
Feature request to add a toggle for "auto periodic backup" to work only on Wi-Fi to avoid mobile data usage.
Another solution to avoid mobile data usage would be to add the ability to schedule the hours / days of backups
Also, it would be great to add a button to synchronise everything manually

Thanks!

**Comment by beradeep** [comment]
Thanks for your feedback! Noted for `v0.5`.

**Comment by beradeep** [comment]
Hi, the latest release is out. Hope you like it 😃 !
