### ISSUE TITLE
Not receiving Id when sending /start in gc.

### ISSUE THREAD

**Issue by muctebanesiri** [beradeep/whitehole#6]

**Comment by Brian2po** [comment]
In the BotFather chat, give it all the permission like this:
![Screenshot_20240716-024056_exteraGram](https://github.com/user-attachments/assets/d2d20a9f-3c11-407f-b5ed-bda24d8487ec)
![Screenshot_20240716-024135_exteraGram](https://github.com/user-attachments/assets/f851c2a6-28ed-417e-a7a6-5040f12dc6b2)

**Comment by muctebanesiri** [comment]
No, Not working even with those settings changed.

**Comment by muctebanesiri** [comment]
> In the BotFather chat, give it all the permission like this: and make sure group privacy is disabled [this is what works for me] 
> ![Screenshot_20240716-024056_exteraGram](https://github.com/user-attachments/assets/d2d20a9f-3c11-407f-b5ed-bda24d8487ec)
> ![Screenshot_20240716-024135_exteraGram](https://github.com/user-attachments/assets/f851c2a6-28ed-417e-a7a6-5040f12dc6b2)
> 

No, Not working even with those settings changed.

**Comment by beradeep** [comment]
Hi @muctebanesiri, the `/start` command will only work when the Whitehole app is running and you're currently on the `Enter Unique Id` Screen.

**Comment by muctebanesiri** [comment]
> Hi @muctebanesiri, the `/start` command will only work when the Whitehole app is running and you're currently on the `Enter Unique Id` Screen.

I am. But still not receiving Id.

**Comment by prono69** [comment]
> > Hi @muctebanesiri, the `/start` command will only work when the Whitehole app is running and you're currently on the `Enter Unique Id` Screen.
> 
> I am. But still not receiving Id.

Did you add the bot as a admin ? And Create GROUP only not Channel.

**Comment by prono69** [comment]
> In the BotFather chat, give it all the permission like this: and make sure group privacy is disabled [this is what works for me] 
> ![Screenshot_20240716-024056_exteraGram](https://github.com/user-attachments/assets/d2d20a9f-3c11-407f-b5ed-bda24d8487ec)
> ![Screenshot_20240716-024135_exteraGram](https://github.com/user-attachments/assets/f851c2a6-28ed-417e-a7a6-5040f12dc6b2)
> 

This will work but you can just simply add the bot as admin .

**Comment by muctebanesiri** [comment]
> > In the BotFather chat, give it all the permission like this: and make sure group privacy is disabled [this is what works for me] 
> > ![Screenshot_20240716-024056_exteraGram](https://github.com/user-attachments/assets/d2d20a9f-3c11-407f-b5ed-bda24d8487ec)
> > ![Screenshot_20240716-024135_exteraGram](https://github.com/user-attachments/assets/f851c2a6-28ed-417e-a7a6-5040f12dc6b2)
> > 
> 
> This will work but you can just simply add the bot as admin .

Nope, tried all the ways even created several bots and groups but no progress.

**Comment by prono69** [comment]
> > > In the BotFather chat, give it all the permission like this: and make sure group privacy is disabled [this is what works for me] 
> > > ![Screenshot_20240716-024056_exteraGram](https://github.com/user-attachments/assets/d2d20a9f-3c11-407f-b5ed-bda24d8487ec)
> > > ![Screenshot_20240716-024135_exteraGram](https://github.com/user-attachments/assets/f851c2a6-28ed-417e-a7a6-5040f12dc6b2)
> > > 
> > 
> > This will work but you can just simply add the bot as admin .
> 
> Nope, tried all the ways even created several bots and groups but no progress.

If you don't mind . @NeoMatrix90 this is my telegram handle . Message me, will try to help you.

**Comment by Muhammad-Aadil** [comment]
I am also facing the same issue!

**Comment by mjain234** [comment]
I am also facing the same issue where I type /start but didn't get any unique id. Also, I have given all the required permission to get that unique id. But still no result. 

https://github.com/user-attachments/assets/fd260da8-84a9-4394-95b7-7e1b7094e7a4

**Comment by beradeep** [comment]
@Muhammad-Aadil @mjain234    https://github.com/beradeep/whitehole/issues/6#issuecomment-2230457083

**Comment by KameBA** [comment]
After trying above suggestions for 15 min, I can get the chat ID using this guide 
https://docs.tracardi.com/qa/how_can_i_get_telegram_bot/

You can use this URL to get the chat id:
https://api.telegram.org/botbotid/getUpdates
api.telegram.org/bot**insert your bot ID from bot father here**/getUpdates
Don't delete **bot** before your bot ID between those "/"
